[package]

name = "balisong"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[lib]
name = "balisong"

[[bin]]
name = "balisong"

[dependencies.time]

[dependencies.regex]

[features]
